### ISSUE TITLE
BUG Error when calling canonical_form() with fewer DMRG sweeps

### ISSUE THREAD

**Issue by mikelgda** [tenpy/tenpy#149]
**Describe the bug**
After using the TwoSiteDMRGEngine, calls to MPS.canonical_form() throw an error. The bug seems to happen when the maximum number of sweeps is set to lower values (50 in this example for my model). It does not happen if ~90 sweeps are done. The system is a 2D honeycomb lattice with spin 1/2 fermion sites based on the Haldane model.

**Error traceback**

```
Traceback (most recent call last):
  File "spin.py", line 301, in <module>
    model, psi = single_run(pstate=pstate,model_params=model_params,save=True,full=True,name=state+str(k))
  File "spin.py", line 155, in single_run
    psi.canonical_form()
  File ".conda/envs/physics/lib/python3.7/site-packages/tenpy/networks/mps.py", line 2647, in canonical_form
    self.canonical_form_infinite(renormalize)
  File ".conda/envs/physics/lib/python3.7/site-packages/tenpy/networks/mps.py", line 2792, in canonical_form_infinite
    Wr, Gl = self._canonical_form_correct_right(i1, Gr, return_Gl_guess=True)
  File ".conda/envs/physics/lib/python3.7/site-packages/tenpy/networks/mps.py", line 3686, in _canonical_form_correct_right
    guess = npc.tensordot(Kr.scale_axis(self.get_SL(i1)**2, 1), Kl, axes=['vR', 'vL'])
TypeError: unsupported operand type(s) for ** or pow(): 'Array' and 'int'
```

**Comment by Jakob-Unfried** [comment]
Same as #170, this should be fixed by now.
