### ISSUE TITLE
BUG: Installation issue with Poetry

### ISSUE THREAD

**Issue by tanlin2013** [tenpy/tenpy#186]
Describe the bug
------------------
Hi, I have been using `poetry` over `pip` for some time. While I'm new to `tenpy`, I found `poetry` failed on the naive installation for `tenpy`, and the error msg says it cannot find module `numpy`, which is indeed installed already in prior. 

However, if I try
```
poetry run pip install physics-tenpy==0.10.0
```
then it shows no error and everything goes properly after the installation. 

Minimal example or code extract
---------------------------------
So by naive installation in `poetry`, I meant 
```
poetry add physics-tenpy==0.10.0
```
or just add `tenpy` in `pyproject.toml` like this
```
[tool.poetry.dependencies]
physics-tenpy = "0.10.0"
```

Error traceback
----------------
Here is the error msg during the installation
```
(myproject-yfra6YSd-py3.10) (base) xxx@xxxs-MacBook-Pro myproject % poetry update
Updating dependencies
Resolving dependencies... (9.2s)

Writing lock file

Package operations: 2 installs, 0 updates, 0 removals

  • Installing cython (0.29.32)
  • Installing physics-tenpy (0.10.0): Failed

  CalledProcessError

  Command '['/Users/xxx/Library/Caches/pypoetry/virtualenvs/myproject-yfra6YSd-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/xxx/Library/Caches/pypoetry/virtualenvs/myproject-yfra6YSd-py3.10', '--no-deps', '/Users/xxx/Library/Caches/pypoetry/artifacts/1a/9c/97/2d24f67187d1eedd8eef831c214adf48932db1d43dd9c5e294704fc1b0/physics-tenpy-0.10.0.tar.gz']' returned non-zero exit status 1.

  at ~/opt/anaconda3/lib/python3.9/subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│ 
       532│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/xxx/Library/Caches/pypoetry/virtualenvs/myproject-yfra6YSd-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/xxx/Library/Caches/pypoetry/virtualenvs/myproject-yfra6YSd-py3.10', '--no-deps', '/Users/xxx/Library/Caches/pypoetry/artifacts/1a/9c/97/2d24f67187d1eedd8eef831c214adf48932db1d43dd9c5e294704fc1b0/physics-tenpy-0.10.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/xxx/Library/Caches/pypoetry/artifacts/1a/9c/97/2d24f67187d1eedd8eef831c214adf48932db1d43dd9c5e294704fc1b0/physics-tenpy-0.10.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [17 lines of output]
        Traceback (most recent call last):
          File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/myproject-yfra6YSd-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/myproject-yfra6YSd-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/myproject-yfra6YSd-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/private/var/folders/9z/xvqzg2q52gd8hxzhj2vgzrpm0000gn/T/pip-build-env-b0rigz_i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/private/var/folders/9z/xvqzg2q52gd8hxzhj2vgzrpm0000gn/T/pip-build-env-b0rigz_i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/private/var/folders/9z/xvqzg2q52gd8hxzhj2vgzrpm0000gn/T/pip-build-env-b0rigz_i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/private/var/folders/9z/xvqzg2q52gd8hxzhj2vgzrpm0000gn/T/pip-build-env-b0rigz_i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 4, in <module>
        ModuleNotFoundError: No module named 'numpy'
        [end of output]
```
I have truncated the rest of msg after the last line, as they are all caused by this line.

Environment
-------------
* poetry 1.2.1
* python 3.10.8 (within the poertry virtual environment)
* numpy 1.23.5

best,
taolin

**Comment by tanlin2013** [comment]
Hi there,

is there any updates on this issue? 

After some googling, I think the problem is related to [PEP517](https://peps.python.org/pep-0517/), which is enabled by construction in `poetry`, so there's no way to turn it off.

So I tried this simple check
```
pip install --use-pep517 --no-binary physics-tenpy physics-tenpy
```
and reproduce the same error message. 

It appears like the only way to resolve this issue is to implement [PEP517](https://peps.python.org/pep-0517/).

References
-----------
https://github.com/python-poetry/poetry/issues/7087
