### ISSUE TITLE
dtype errors on Windows

### ISSUE THREAD

**Issue by JerryChen97** [tenpy/tenpy#30]
```
PS D:\MyWorks\TensorNetworks> nosetests
....EEEEEEEEE.D:\MyWorks\TensorNetworks\tenpy\linalg\np_conserved.py:2414: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_block = old_block[block_slice].reshape(new_block_shape)
.........E.....E.EED:\MyWorks\TensorNetworks\tenpy\linalg\np_conserved.py:2414: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_block = old_block[block_slice].reshape(new_block_shape)
EEEEEE..E.EEEEEE.EEEEEEEEE.EEEEE.EED:\MyWorks\TensorNetworks\tenpy\tools\params.py:115: UserWarning: unused parameters for TEBD trunc_params:
['chi_max', 'svd_min']
  warnings.warn(msg.format(keys=sorted(unused), descr=warn))
D:\MyWorks\TensorNetworks\tenpy\tools\params.py:115: UserWarning: unused parameters for TEBD:
['N_steps', 'disentangle', 'dt']
  warnings.warn(msg.format(keys=sorted(unused), descr=warn))
ED:\MyWorks\TensorNetworks\tenpy\tools\params.py:115: UserWarning: unused parameter ['disentangle'] for TEBD

  warnings.warn(msg.format(keys=sorted(unused), descr=warn))
E.........E.....D:\MyWorks\TensorNetworks\tenpy\linalg\np_conserved.py:2414: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_block = old_block[block_slice].reshape(new_block_shape)
.D:\MyWorks\TensorNetworks\tenpy\linalg\np_conserved.py:2414: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  new_block = old_block[block_slice].reshape(new_block_shape)
.EEE.ED:\MyWorks\TensorNetworks\tenpy\tools\params.py:115: UserWarning: unused parameters for TEBD trunc_params:
['chi_max', 'trunc_cut']
  warnings.warn(msg.format(keys=sorted(unused), descr=warn))
D:\MyWorks\TensorNetworks\tenpy\tools\params.py:115: UserWarning: unused parameters for TEBD:
['delta_tau_list', 'dt', 'max_error_E', 'order']
  warnings.warn(msg.format(keys=sorted(unused), descr=warn))
ED:\MyWorks\TensorNetworks\tenpy\tools\params.py:115: UserWarning: unused parameters for TEBD trunc_params:
['chi_max', 'trunc_cut']
  warnings.warn(msg.format(keys=sorted(unused), descr=warn))
D:\MyWorks\TensorNetworks\tenpy\tools\params.py:115: UserWarning: unused parameters for TEBD:
['delta_tau_list', 'dt', 'max_error_E', 'order']
  warnings.warn(msg.format(keys=sorted(unused), descr=warn))
....D:\MyWorks\TensorNetworks\tenpy\tools\process.py:51: UserWarning: No tool to determine memory_usage
  warnings.warn("No tool to determine memory_usage")
........EE....E
======================================================================
ERROR: test_dmrg.test_dmrg(4, 'finite', 'EngineCombine', None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\chenyushao\appdata\local\programs\python\python37\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\MyWorks\TensorNetworks\tests\test_dmrg.py", line 58, in check_dmrg
    res = dmrg.run(psi, M, dmrg_pars)
  File "D:\MyWorks\TensorNetworks\tenpy\algorithms\dmrg.py", line 228, in run
    max_trunc_err, max_E_trunc = engine.sweep(meas_E_trunc=(i + 1 == N_sweeps_check))
  File "D:\MyWorks\TensorNetworks\tenpy\algorithms\dmrg.py", line 474, in sweep
    i0, upd_env[0], upd_env[1], optimize=optimize, meas_E_trunc=meas_E_trunc)
  File "D:\MyWorks\TensorNetworks\tenpy\algorithms\dmrg.py", line 528, in update_bond
    theta = self.prepare_diag(i0, update_LP, update_RP)
  File "D:\MyWorks\TensorNetworks\tenpy\algorithms\dmrg.py", line 872, in prepare_diag
    [['vR*', 'p0'], ['vR', 'p0*']], pipes=[pipeL, pipeL.conj()], new_axes=[0, -1])
  File "D:\MyWorks\TensorNetworks\tenpy\linalg\np_conserved.py", line 1206, in combine_legs
    return res.combine_legs(tr_combine_legs, new_axes=new_axes, pipes=pipes)
  File "D:\MyWorks\TensorNetworks\tenpy\linalg\np_conserved.py", line 1211, in combine_legs
    res = self._combine_legs_worker(combine_legs, new_axes, pipes)
  File "D:\MyWorks\TensorNetworks\tenpy\linalg\np_conserved.py", line 2337, in _combine_legs_worker
    out=qdata[:, na])  # write the result directly into qdata
  File "c:\users\chenyushao\appdata\local\programs\python\python37\lib\site-packages\numpy\core\fromnumeric.py", line 189, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "c:\users\chenyushao\appdata\local\programs\python\python37\lib\site-packages\numpy\core\fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "c:\users\chenyushao\appdata\local\programs\python\python37\lib\site-packages\numpy\core\fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```

I followed the instructions in the documentation and came across this TypeError on the above when I tried running `$nosetests`.
My configuration:
Windows 10
python 3 (anaconda)
numpy 1.16.2
scipy 1.2.1
Bottleneck 1.2.1
mkl 2019.0

**Comment by jhauschild** [comment]
Looks like a conversion problem between 64bit and 32bit integers.
I guess you use a 64 bit machine?
As far as I can see, you did not compile the Cython parts, did you?

**Comment by JerryChen97** [comment]
> 
> 
> Looks like a conversion problem between 64bit and 32bit integers.
> I guess you use a 64 bit machine?
> As far as I can see, you did not compile the Cython parts, did you?

Oh I did forget to compile Cython... lol

**Comment by jhauschild** [comment]
But it should also work without compiling....

**Comment by JerryChen97** [comment]
> 
> 
> But it should also work without compiling....

I will try compiling and check other possible missing steps...

**Comment by jhauschild** [comment]
Did you download the newest version from git?

**Comment by JerryChen97** [comment]
`print(tenpy.__full_version__)
v0.3.0 git unknown using python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] with numpy 1.16.2, scipy 1.2.1`

**Comment by jhauschild** [comment]
well, version 0.3.0 is over a year old by now, so this doesn't really help... 
When did you download the code?

**Comment by JerryChen97** [comment]
??? just this morning I think

**Comment by Lschoon** [comment]
If I may butt in: that version readout is given because `version.py` cannot find git on your machine, thus defaults to the hardcoded default `0.3.0`. Are you using git to link your local machine to your GitHub repository? Can you confirm your local repository is up to date with the one on GitHub.

**Comment by jhauschild** [comment]
That's odd... Does the file tenpy/linalg/np_conserved look like [this file](https://github.com/tenpy/tenpy/blob/master/tenpy/linalg/np_conserved.py)?
Or did you download the latest release as a zip from https://github.com/tenpy/tenpy/releases? Than it's clear that this is old...

**Comment by JerryChen97** [comment]
> 
> 
> If I may butt in: that version readout is given because `version.py` cannot find git on your machine, thus defaults to the hardcoded default `0.3.0`. Are you using git to link your local machine to your GitHub repository? Can you confirm your local repository is up to date with the one on GitHub?

Oh I checked the version.py and then checked my git to find that indeed I myself could not find git...
However I installed git this morning for sure and set up the user info...
Really odd...
I will switch to my linux and try all the installation again...

**Comment by JerryChen97** [comment]
> 
> 
> That's odd... Does the file tenpy/linalg/np_conserved look like [this file](https://github.com/tenpy/tenpy/blob/master/tenpy/linalg/np_conserved.py)?
> Or did you download the latest release as a zip from https://github.com/tenpy/tenpy/releases? Than it's clear that this is old...

They are exactly the same...

**Comment by Lschoon** [comment]
> > If I may butt in: that version readout is given because `version.py` cannot find git on your machine, thus defaults to the hardcoded default `0.3.0`. Are you using git to link your local machine to your GitHub repository? Can you confirm your local repository is up to date with the one on GitHub?
> 
> Oh I checked the version.py and then checked my git to find that indeed I myself could not find git...
> However I installed git this morning for sure and set up the user info...
> Really odd...
> I will switch to my linux and try all the installation again...

If git is installed correctly, I am not sure why `version.py` cannot find it. You might need to set a system variable, e.g. $PATH. 
Did you get tenpy on your local machine via git, or by downloading a zip, as Johannes suggested?

If switching to Linux is an option, that might indeed be easier.

**Comment by JerryChen97** [comment]
> > > If I may butt in: that version readout is given because `version.py` cannot find git on your machine, thus defaults to the hardcoded default `0.3.0`. Are you using git to link your local machine to your GitHub repository? Can you confirm your local repository is up to date with the one on GitHub?
> > 
> > 
> > Oh I checked the version.py and then checked my git to find that indeed I myself could not find git...
> > However I installed git this morning for sure and set up the user info...
> > Really odd...
> > I will switch to my linux and try all the installation again...
> 
> If git is installed correctly, I am not sure why `version.py` cannot find it. You might need to set a system variable, e.g. $PATH.
> Did you get tenpy on your local machine via git, or by downloading a zip, as Johannes suggested?
> 
> If switching to Linux is an option, that might indeed be easier.

I remember that I downloaded them through git this morning

**Comment by Lschoon** [comment]
I will attempt to replicate the error on a Windows machine, but it will take a while to get to one.

Meanwhile, do try installing tenpy on Linux and see if that works.

**Comment by JerryChen97** [comment]
> I will attempt to replicate the error on a Windows machine, but it will take a while to get to one.
> 
> Meanwhile, do try installing tenpy on Linux and see if that works.

Thank you very much.
Currently I am going to use tenpy to try to compute something for my thesis so I have to pause my testing on Windows for a while until I am sure that I can successfully graduate...
I will inform you once I have any new findings on Windows.

**Comment by Lschoon** [comment]
I had forgotten how hard it was to get Python to work right on a Windows PC...

So far I hav not replicated your exact error, but I am getting a similar and potentially related error:

```
======================================================================
ERROR: test_dmrg.test_dmrg(2, 'infinite', 'EngineFracture', None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda2\envs\idp3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\Leon\tenpy\tests\test_dmrg.py", line 62, in check_dmrg
    res = dmrg.run(psi, M, dmrg_pars)
  File "C:\Users\Leon\tenpy\tenpy\algorithms\dmrg.py", line 176, in run
    engine = Engine_class(psi, model, DMRG_params)
  File "C:\Users\Leon\tenpy\tenpy\algorithms\dmrg.py", line 302, in __init__
    self.init_env(model) # calls reset_stats
  File "C:\Users\Leon\tenpy\tenpy\algorithms\dmrg.py", line 358, in init_env
    self.environment_sweeps(start_env)
  File "C:\Users\Leon\tenpy\tenpy\algorithms\dmrg.py", line 558, in environment_sweeps
    self.sweep(optimize=False)
  File "C:\Users\Leon\tenpy\tenpy\algorithms\dmrg.py", line 598, in sweep
    i0, upd_env[0], upd_env[1], optimize=optimize, meas_E_trunc=meas_E_trunc)
  File "C:\Users\Leon\tenpy\tenpy\algorithms\dmrg.py", line 668, in update_bond
    self.update_LP(i0, U)  # (requires updated B)
  File "C:\Users\Leon\tenpy\tenpy\algorithms\dmrg.py", line 1230, in update_LP
    self.env.get_LP(i0 + 1, store=True)  # as implemented directly in the environment
  File "C:\Users\Leon\tenpy\tenpy\networks\mpo.py", line 840, in get_LP
    return super().get_LP(i, store)
  File "C:\Users\Leon\tenpy\tenpy\networks\mps.py", line 2848, in get_LP
    LP = self._contract_LP(j, LP)
  File "C:\Users\Leon\tenpy\tenpy\networks\mpo.py", line 905, in _contract_LP
    LP = npc.tensordot(self.H.get_W(i), LP, axes=(['p*', 'wL'], ['p', 'wR']))
  File "C:\Users\Leon\tenpy\tenpy\linalg\np_conserved.py", line 3177, in tensordot
    res = _tensordot_worker(a, b, axes)
  File "tenpy\linalg\_npc_helper.pyx", line 1405, in tenpy.linalg._npc_helper._tensordot_worker
  File "tenpy\linalg\_npc_helper.pyx", line 506, in tenpy.linalg._npc_helper._find_row_differences
ValueError: Buffer dtype mismatch, expected 'QTYPE_t' but got 'long long'
-------------------- >> begin captured stdout << ---------------------
parameter 'engine'='EngineFracture' for DMRG
parameter 'verbose'=5 for DMRG
parameter 'lanczos_params'={'reortho': True, 'N_cache': 20} for DMRG
parameter 'trunc_params'={'svd_min': 1e-10} for DMRG
parameter 'LP'=None (default) for DMRG
parameter 'RP'=None (default) for DMRG
parameter 'LP_age'=0 (default) for DMRG
parameter 'RP_age'=0 (default) for DMRG
parameter 'orthogonal_to'=[] (default) for DMRG
parameter 'sweep_0'=0 (default) for DMRG
parameter 'chi_list'={0: 10, 5: 30} for DMRG
Setting chi_max = 10
parameter 'start_env'=1 for DMRG
Updating environment

--------------------- >> end captured stdout << ----------------------
```

This is a fresh git clone, with cythonized code. `ValueError: Buffer dtype mismatch, expected 'QTYPE_t' but got 'long long'` suggests this is another dtype error.

**Comment by jhauschild** [comment]
does it work if you  `export TENPY_OPTIMIZE=0` (which disables the Cython stuff)?

**Comment by Lschoon** [comment]
That indeed removes the errors:
```
>nosetests
C:\Users\Leon\tenpy\tenpy\tools\optimization.py:277: UserWarning: Don't load compiled cython code due to TENPY_OPTMIZE. Code will run a bit slower.
  warnings.warn("Don't load compiled cython code due to TENPY_OPTMIZE. "
.......C:\Users\Leon\tenpy\tenpy\tools\process.py:51: UserWarning: No tool to determine memory_usage
  warnings.warn("No tool to determine memory_usage")
.
<TRUNCATED>
..................................C:\Users\Leon\tenpy\tenpy\models\hofstadter.py:106: UserWarning: Magnetic unit cell not (fully) specified.
  warnings.warn("Magnetic unit cell not (fully) specified.")
<TRUNCATED>
.................................................................................................F.F............C:\Users\Leon\tenpy\tenpy\tools\process.py:51: UserWarning: No tool to determine memory_usage
  warnings.warn("No tool to determine memory_usage")
.....................
======================================================================
FAIL: just try to import the lapack library on the local system.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda2\envs\idp3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\Leon\tenpy\tests\test_svd_robust.py", line 23, in test_CLAPACK_import
    assert(False)
AssertionError:
-------------------- >> begin captured stdout << ---------------------
Couldn't find LAPACK library for 'gesvd' workaround.
Tried: ['libLAPACK.dylib', 'libmkl_rt.so', 'libmkl_intel_lp64.so', 'liblapack.so', 'libopenblas.dll', None]
(Not an issue if you have scipy >= 0.18.0)

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_svd_robust.test_svd(<function svd_gesvd at 0x000002BE6A11F378>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda2\envs\idp3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\Leon\tenpy\tests\test_svd_robust.py", line 58, in check_svd_function
    assert(False)
AssertionError:
-------------------- >> begin captured stdout << ---------------------
dtype =  <class 'numpy.float32'>
m, n =  1 1
Couldn't find LAPACK library for 'gesvd' workaround.
Tried: ['libLAPACK.dylib', 'libmkl_rt.so', 'libmkl_intel_lp64.so', 'liblapack.so', 'libopenblas.dll', None]
(Not an issue if you have scipy >= 0.18.0)

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 186 tests in 1152.630s

FAILED (failures=2)
```
I am left with a bunch of UserWarnings (repeating ones removed from the output above, the ones from `hofstadter.py` are expected). and two failed tests that have something to do with LAPACK, which is a different issue than this thread is about.

**Comment by jhauschild** [comment]
@Lschoon does this fix  solve the problem for you?

**Comment by Lschoon** [comment]
The error from my [original message](https://github.com/tenpy/tenpy/issues/30#issuecomment-482151060) is gone, but I still get 21 repeats of the following error (which looks like a similar dtype issue):
```
======================================================================
ERROR: test_model_spins_nnn.test_SpinChainNNN
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda2\envs\idp3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\Leon\tenpy\tests\test_model_spins_nnn.py", line 15, in test_SpinChainNNN
    'bc_MPS': ['finite', 'infinite']
  File "C:\Users\Leon\tenpy\tests\test_model.py", line 69, in check_general_model
    check_model_sanity(M)
  File "C:\Users\Leon\tenpy\tests\test_model.py", line 43, in check_model_sanity
    test_mpo.check_hermitian(M.H_MPO)
  File "C:\Users\Leon\tenpy\tests\test_mpo.py", line 30, in check_hermitian
    trHH = npc.tensordot(W, W.replace_label('wR', 'wR*'), axes=[['p', 'p*'], ['p*', 'p']])
  File "C:\Users\Leon\tenpy\tenpy\linalg\np_conserved.py", line 3185, in tensordot
    res = _tensordot_worker(a, b, axes)
  File "tenpy\linalg\_npc_helper.pyx", line 1497, in tenpy.linalg._npc_helper._tensordot_worker
ValueError: Buffer dtype mismatch, expected 'intp_t' but got 'long'
-------------------- >> begin captured stdout << ---------------------
----------------------------------------
check_model_sanity with following parameters:
{'hz': 0.5, 'Jx': -2.0, 'Jy': -2.0, 'Jz': 0.4, 'L': 4, 'conserve': None, 'bc_MPS': 'finite'}
parameter 'lattice'='Chain' for SpinChainNNN
parameter 'bc_MPS'='finite' for SpinChainNNN
parameter 'conserve'=None for SpinChainNNN
parameter 'L'=4 for SpinChainNNN
parameter 'Jx'=-2.0 for SpinChainNNN
parameter 'Jy'=-2.0 for SpinChainNNN
parameter 'Jz'=0.4 for SpinChainNNN
parameter 'hz'=0.5 for SpinChainNNN

--------------------- >> end captured stdout << ----------------------
```

**Comment by jhauschild** [comment]
okay, again a very simple fix...
I'm now able to run all the tests successfully both with and without the compiled stuff, on a 64 windows machine where `np.arange(4)` gives 32-bit integers, probably due to the used python version.
During compilation a bunch of warnings appear saying that we convert intp_t into int, but I think it's fine now.
Can anybody confirm?

**Comment by Lschoon** [comment]
Confirmed fix, recompiled code now runs all nosetests without errors.
