### ISSUE TITLE
 New version 0.11.0 can not use misc.setup_logging() like 0.10.0

### ISSUE THREAD

**Issue by Kwhuang97** [tenpy/tenpy#357]
**Describe the bug**
l find that in tenpy-0.11.0.The misc can not work like tenpy-0.10.0

**Minimal example or code extract**
```python
from tenpy.tools import misc
misc.setup_logging()
```
**Output**
```python
Traceback (most recent call last):
  File "/softwares/miniconda/envs/tenpy-0.11.0/lib/python3.11/logging/config.py", line 573, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/softwares/miniconda/envs/tenpy-0.11.0/lib/python3.11/logging/config.py", line 757, in configure_handler
    result = factory(**kwargs)
             ^^^^^^^^^^^^^^^^^
  File "/softwares/miniconda/envs/tenpy-0.11.0/lib/python3.11/logging/__init__.py", line 1161, in __init__
    filename = os.fspath(filename)
               ^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/softwares/miniconda/envs/tenpy-0.11.0/lib/python3.11/site-packages/tenpy/tools/misc.py", line 933, in setup_logging
    logging.config.dictConfig(dict_config)
  File "/softwares/miniconda/envs/tenpy-0.11.0/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/softwares/miniconda/envs/tenpy-0.11.0/lib/python3.11/logging/config.py", line 580, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'to_file'
>>> miscfrom tenpy.tools import miscmisc.setup_logging()
  File "<stdin>", line 1
    miscfrom tenpy.tools import miscmisc.setup_logging()
             ^^^^^
SyntaxError: invalid syntax
```

**Comment by Jakob-Unfried** [comment]
Hi, this is already fixed by 8f2390b.
The fix is not part of a new release yet, though.
In the meantime you can do `misc.setup_logging(filename=None)`
