### ISSUE TITLE
BUG `LegCharge` equality testing too strict for Z_N charges

### ISSUE THREAD

**Issue by attila-i-szabo** [tenpy/tenpy#470]
**Describe the bug**
When trying to contract two `LegCharge`s with non-U(1) symmetry (in my case, Z2), I get errors when trying to contract legs that are only equal mod N.

**Minimal example or code extract**
Show how you call the code that is failing. Include it in backticks like this:
```python
import tenpy
tenpy.show_config()

from tenpy.linalg.charges import ChargeInfo, LegCharge

z2 = ChargeInfo([2])
leg = LegCharge(z2, [0,1,2], [[0],[1]])

leg.test_equal(leg.conj())
```
If you think it's helpfull, you can also include output.

**Error traceback**
If applicable, copy-paste (the first and last part of) the error traceback
```
Traceback (most recent call last):
  File "/home/attila/Science/MF-MPS/mnwe.py", line 9, in <module>
    leg.test_equal(leg.conj())
  File "/home/attila/.local/lib/python3.10/site-packages/tenpy/linalg/charges.py", line 843, in test_equal
    raise ValueError("incompatible LegCharge\n" + side_by_side)
ValueError: incompatible LegCharge
self    | other  
 +1     |  -1    
0 [[0]  | 0 [[0] 
1  [1]] | 1  [1]]
2       | 2      
```

**Comment by Jakob-Unfried** [comment]
Fixed now. Thanks!
