### ISSUE TITLE
LinAlgError raised when running 'haldane_FCI.py' in examples

### ISSUE THREAD

**Issue by JefferyWangSH** [tenpy/tenpy#476]
**Describe the bug**
I am new to tenpy and also DMRG, trying to run the example of [Haldane's FCI model](https://github.com/tenpy/tenpy/blob/fae8bcfa66f9d978d4aa9f4f6f17eea25c851c9e/examples/chern_insulators/haldane_FCI.py). All I did was simply copy/paste the example and attempt to execute it locally. However I encountered a **LinAlgError: Eigenvalues did not converge**. (In fact, none of the three haldane*.py files works as expected with the same error.)

**Error traceback**
```
Traceback (most recent call last):
  File "/Users/jefferywang/Desktop/fci.py", line 157, in <module>
    data = run(model_params)
           ^^^^^^^^^^^^^^^^^
  File "/Users/jefferywang/Desktop/fci.py", line 94, in run
    E, psi = eng.run()
             ^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/algorithms/dmrg.py", line 459, in run
    return super().run()
           ^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/algorithms/mps_common.py", line 779, in run
    result = self.run_iteration()
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/algorithms/dmrg.py", line 307, in run_iteration
    self.sweep(meas_E_trunc=False)
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/algorithms/dmrg.py", line 544, in sweep
    return super().sweep(optimize)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/algorithms/mps_common.py", line 379, in sweep
    update_data = self.update_local(theta, optimize=optimize)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/algorithms/dmrg.py", line 581, in update_local
    E0, theta, N, ov_change = self.diag(theta)
                              ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/algorithms/dmrg.py", line 756, in diag
    E, theta, N = LanczosGroundState(self.eff_H, theta_guess, self.lanczos_params).run()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/linalg/krylov_based.py", line 481, in run
    N = self._build_krylov()
        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/linalg/krylov_based.py", line 515, in _build_krylov
    self._calc_result_krylov(k)
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/linalg/krylov_based.py", line 564, in _calc_result_krylov
    E_kr, v_kr = np.linalg.eigh(h[:k + 1, :k + 1])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/numpy/linalg/linalg.py", line 1487, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/numpy/linalg/linalg.py", line 118, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.LinAlgError: Eigenvalues did not converge
/opt/homebrew/anaconda3/envs/tenpy/lib/python3.12/site-packages/tenpy/tools/params.py:230: UserWarning: unused options for config TwoSiteDMRGEngine:
['max_E_err', 'max_S_err']
  warnings.warn(msg.format(keys=sorted(unused), name=self.name))
```

Here is  my tenpy config if it's necessary
```
tenpy 1.0.0 (compiled without HAVE_MKL),
git revision 8c868ba70e526f1f00561470d58fcbaddb1b4e48 using
python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]
numpy 1.26.4, scipy 1.12.0
```
and i am working on MacOS 15.1.1.

Any help will be greatly appreciated!

**Comment by JefferyWangSH** [comment]
Problem solved by rebuilding TenPy from source, so going to close this issue...
